source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BetterSegmentedControl_Example' do
  pod 'BetterSegmentedControl', :path => '../'

  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
end

target 'BetterSegmentedControl_Tests' do
  pod 'BetterSegmentedControl', :path => '../'

  pod 'Quick', '1.2.0'
  pod 'Nimble', '7.0.2'
end
